---
#
# PLEASE NOTE: Managed workflow - do not change manually
#
name: Release

on:
  workflow_dispatch:
    inputs:
      dryRun:
        type: boolean
        description: "Dry-Run"
        default: false

concurrency:
  # only run one publishing at a time to avoid conflicts
  group: publish-${{ github.ref }}

jobs:
  publish:
    # Only on main repository (don't release on forks)
    if: github.repository_owner == 'wetransform-os'

    uses: wetransform/gha-workflows/.github/workflows/gradle-library-publish.yml@d013e58794766536ac0bb90fbda477a21ed9d4d0 # v3.7.0
    with:
      semantic-release-dryrun: ${{ inputs.dryRun }}
      java-version: 17
      multi-module: false
      semantic-release: true
      skip-scan: false
    secrets:
      WETF_ARTIFACTORY_USER: ${{ secrets.WETF_ARTIFACTORY_USER }}
      WETF_ARTIFACTORY_PASSWORD: ${{ secrets.WETF_ARTIFACTORY_PASSWORD }}
      SLACK_NOTIFICATIONS_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
      WE_RELEASE_GITHUB_APP_ID: ${{ secrets.WE_RELEASE_GITHUB_APP_ID }}
      WE_RELEASE_GITHUB_PRIVATE_KEY: ${{ secrets.WE_RELEASE_GITHUB_PRIVATE_KEY }}
